version: '2'
services:

  db:
    container_name: odoo12_db_ce
    image: postgres:10
    ports:
      - "5070:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    restart: always

  web:
    container_name: odoo12_web_ce
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "12000:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - web-data:/var/lib/odoo
    restart: always

volumes:
  db-data: null
  web-data: null
